#![allow(clippy::large_enum_variant)]
#[macro_use]
mod group;
#[macro_use]
pub mod token;
mod attr;
mod bigint;
pub mod buffer;
mod classify;
mod custom_keyword;
mod custom_punctuation;
mod data;
pub use crate::data::{Field, FieldNamed, FieldUnnamed};
mod derive;
mod drops;
mod error;
pub use crate::error::{Error, Result};
mod expr;
pub use crate::expr::{Arm, Expr};
pub mod ext;
mod file;
pub use crate::file::{File, parse_file};
mod generics;
mod ident;
pub use crate::ident::Ident;
mod item;
pub use crate::item::Item;
mod lifetime;
mod lit;
pub use crate::lit::Lit;
mod lookahead;
mod mac;
mod op;
pub mod parse;
mod pat;
pub use pat::{Pat, PatMulti};
mod path;
mod precedence;
mod punctuated;
mod restriction;
pub use crate::restriction::Visibility;
mod sealed;
mod span;
mod stmt;
pub use crate::stmt::Stmt;
mod thread;
mod ty;
pub use crate::ty::Type;
#[path = "export.rs"]
pub mod __private;
mod node;
mod verbatim;
mod whitespace;
pub use node::{Kind, Node, parse_node_with_kind};
pub use parse::{ParseCtx, parse_ctx, parse_str, parse_with_ctx};
pub use proc_macro2::{TokenStream, TokenTree};
